# Generated by Django 5.0 on 2023-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='course',
            field=models.CharField(blank=True, max_length=100, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='id_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='name_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='phone_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
    ]
