# Generated by Django 5.0 on 2023-12-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_telegrambot_course_telegrambot_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
