# Generated by Django 5.0 on 2023-12-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_telegrambot_course_alter_telegrambot_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Курс'),
        ),
    ]
