# Generated by Django 5.0 on 2023-12-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_telegrambot_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
