# Generated by Django 5.0 on 2023-12-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_telegrambot_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ на рассылку'),
        ),
    ]
