# Generated by Django 5.0 on 2023-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_telegrambot_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sending', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
            ],
        ),
    ]
